MISSION, TOOLS, GAZEBO
uf-mil/SubjuGator pull request #184
Opened 2017-01-03 03:39 UTC by mattlangford

This was more an adaptation rather than a port. 
- The mission system is still mainly code from last year, with some additions that were based on Navigator, mainly the yaml config for vision services. There are some rules about what your perception nodes need to include that are worth looking at in the comments in the main `sub_singleton` file.
- Rviz config! It's pretty new and I only used it in sim so there could be more things we need to show on there.
- fprint! Everyone's favorite printing method. I'm going to make some more commits that transition a lot of the old nodes to use fprint.
- `sub8_ros_tools` and `sub8_misc_tools` used to require you to import both to use tools in both. Now all tools from both can be imported by importing `sub8_tools`.

2017-01-06 21:56 UTC, DSsoto approved these changes
Looks good, minor comments.

2017-01-06 21:56 UTC, DSsoto commented on command/sub8_missions/nodes/move_command
> +        help='Move type. See lqrrt documentation for info on how to use this.')
This lqrrrt stuff is not supported by the sub currently.

2017-01-06 21:56 UTC, DSsoto commented on command/sub8_missions/tools/waypoint_utility.py
> +            position[2] = -0.5
A warning here would be nice

2017-01-06 21:56 UTC, DSsoto commented on command/sub8_missions/nodes/move_command
> +    elif args.command == "stop":
Can you add a page to the wiki for all these new subc commands?

2017-01-07 21:38 UTC, kev-the-dev requested changes
Some quick fixes to add at some point in addition to David's stuff

2017-01-07 21:38 UTC, ironmig commented on command/sub8_missions/missions/tx_test.py
> +    print "Goiung"
yeah?

2017-01-07 21:38 UTC, ironmig commented on command/sub8_missions/nodes/move_command
> +SHORTHAND = {"f": "forward", "b": "backward", "l": "left", "r": "right", "yl": "yaw_left", "yr": "yaw_right"}
be nice to add `"d": "down", "u": "up"`

2017-01-07 21:38 UTC, ironmig commented on command/sub8_missions/nodes/move_command
> +        help="How fast to execute the move.")
Does this work on the sub? Also, please specify in the help string what this number represents (meters/second or proportion of max speed?)

2017-01-07 21:55 UTC, mattlangford commented on command/sub8_missions/nodes/move_command
> +    elif args.command == "stop":
Will do

2017-01-07 21:58 UTC, mattlangford commented on command/sub8_missions/nodes/move_command
> +        help="How fast to execute the move.")
Yes, it's m/s (I added that to the help printout)

2017-01-07 23:33 UTC, kev-the-dev approved these changes

2017-01-07 23:34 UTC, merged