SIMULATION: follow trajectory perfectly in gazebo
uf-mil/SubjuGator pull request #232
Opened 2017-05-05 02:54 UTC by ironmig

* disable buoyency/turbulence/thruster simulation so the position of SubjuGator is always the latest pose generated by c3

Addresses #231

2017-05-05 05:24 UTC, DSsoto requested changes
Undo the removal of the torpedo board and I'll be ready to approve if it runs on my machine without issues. (will do tomorrow)

2017-05-05 05:24 UTC, DSsoto commented on simulation/sub8_gazebo/models/sub8/sub8.sdf
> +    <!-- Commend out to enable physics simulated controls -->
Coment

2017-05-05 05:24 UTC, DSsoto commented on simulation/sub8_gazebo/models/sub8/sub8.sdf
> +    <!-- Uncomment to enable physics simulated controls
Contradicts above comment

2017-05-05 05:24 UTC, DSsoto commented on simulation/sub8_gazebo/launch/duck.launch
> -  <!-- We need to spawn a torpedo that the launcher script can use to shoot -->
I don't know why you're removing this.

2017-05-05 19:54 UTC, ironmig commented on simulation/sub8_gazebo/models/sub8/sub8.sdf
> +    <!-- Uncomment to enable physics simulated controls
If you want to simulate controls with physics, you comment out the state publisher and uncomment the buoyancy and thruster plugins.

2017-05-07 03:42 UTC, DSsoto commented on simulation/sub8_gazebo/models/sub8/sub8.sdf
> +    <!-- Uncomment to enable physics simulated controls
My mistake, I thought they were referring to the same code.

2017-05-07 05:14 UTC, DSsoto approved these changes

2017-05-07 05:20 UTC, DSsoto commented
Ran sim with changes, looks good!

2017-05-07 05:20 UTC, merged