MISSIONS: add teleport list option, proxies for passive sonar and actuators
uf-mil/SubjuGator pull request #286
Opened 2017-06-23 21:22 UTC by ironmig

* Add an option to the subm teleport command. So ```subm tp list``` / ```subm tp l``` will print a nicely formated list of available teleport locations in case you forget the option in the YAML.
* Added passive sonar proxy, made to abstract the service calls that talk to PassiveSonarOS (once merged) so missions code can do ```sub.pasive_sonar.get_position()```, etc
* Added actuator proxy, made to extract the service calls that talk to the actuator board driver, so mission code can do ```sub.open_gripper()```, ```sub.shoot_torpedo()```, etc.

2017-06-26 14:20 UTC, Grymestone commented
The subc teleport list looks great, that was a good idea.

2017-06-26 19:57 UTC, DSsoto requested changes
Have you tested the proxys at all?

2017-06-26 19:57 UTC, DSsoto commented on command/sub8_missions/sub8/sub_singleton.py
> +        self.passive_sonar = _PassiveSonarProxy(self.nh, 'hydrophones')
The namespace should be `/passive_sonar`

2017-06-26 19:57 UTC, DSsoto commented on command/sub8_missions/sub8/sub_singleton.py
> +        return self.set('torped2', True)
typo?

2017-06-26 21:29 UTC, ironmig commented
I think I'm going to separate the teleport changes to yet another PR, because the passive sonar proxy will break missions until passive sonar OS is merged.

2017-06-26 21:45 UTC, DSsoto commented
Good idea.

2017-06-27 22:03 UTC, ironmig commented
EDITS:
* put the TP stuff in a different PR as it's unrelated #291 
* removed passive sonar proxy, as it will break things until PassiveSonarOS is merged. I still have it [on this branch](https://github.com/ironmig/SubjuGator/blob/passive-sonar/command/sub8_missions/sub8/sub_singleton.py)
* got the actuator driver up and running again in SIM, and a mission to test the actuator proxy

2017-06-27 23:54 UTC, DSsoto approved these changes

2017-06-27 23:54 UTC, DSsoto commented on command/sub8_missions/missions/test_actuators.py
> +        fprint('Failed 1 or more actuator calls', msg_color='red')
This is not as usefull if it doesn't say what actuator call failed

2017-06-28 17:47 UTC, ironmig commented on command/sub8_missions/missions/test_actuators.py
> +        fprint('Failed 1 or more actuator calls', msg_color='red')
It will say where it failed in the errback when the service fails.

2017-06-28 17:49 UTC, merged