START_GATE
uf-mil/SubjuGator pull request #293
Opened 2017-06-28 20:14 UTC by RustyBamboo

- More thorough gate segmentation
- Uses stereo
Still have a few TODOs...

2017-06-29 00:39 UTC, DSsoto reviewed
A couple of comments from the first half of the PR since this one is pretty long.

Be sure to think about other people debugging your code at competition between runs at competition. You wouldn't want to be debugging code where all the poses are just called 'pose' or transforms 'tft'.

We should really have a class for an arbitrary stereo perception node in c++ that everyone could inherit from, there's (through no fault of yours) a lot of repeated code here. Oh well, I guess we have to mind our priorities.

2017-06-29 00:39 UTC, DSsoto commented on command/sub8_missions/missions/start_gate.py
> +    HOW_MANY = 20
I don't think this is great naming practice. Maybe `FEATURE_COUNT`?

2017-06-29 00:39 UTC, DSsoto commented on command/sub8_missions/missions/start_gate.py
> +        self._how_many_points = 0
Sorry for nitpicking but this just looks odd to me, I'd suggest `point_count`

2017-06-29 00:39 UTC, DSsoto commented on command/sub8_missions/missions/start_gate.py
> +            Go directly in front of gate
You should use a single line comment here

2017-06-29 00:39 UTC, DSsoto commented on command/sub8_missions/missions/start_gate.py
> +    def search_patten(self):
How come you're not using this search pattern?

2017-06-29 00:39 UTC, DSsoto commented on command/sub8_missions/missions/start_gate.py
> +            Go through the gate
Same as above

2017-06-29 00:39 UTC, DSsoto commented on command/sub8_missions/missions/start_gate.py
> +        fprint('Going infront of gate {}'.format(transformed_before_gate._p))
Missing a space here

2017-06-29 00:39 UTC, DSsoto commented on command/sub8_missions/missions/start_gate.py
> +        transformed_before_gate = transform * tft
Don't say transformed, specify the frame.

2017-06-29 00:39 UTC, DSsoto commented on command/sub8_missions/missions/start_gate.py
>      def run_mission(self):
This `run_mission` function is pretty long, you should refactor into smaller chunks.

2017-06-29 00:39 UTC, DSsoto commented on perception/sub8_perception/include/sub8_perception/start_gate.hpp
> +  void combinations(uint8_t n, uint8_t k, std::vector<std::vector<uint8_t>> &idx_array);
This really should go in mil_tools, not here. Also don't forget to attribute things you didn't code yourself.

2017-06-29 00:39 UTC, DSsoto commented on perception/sub8_perception/include/sub8_perception/start_gate.hpp
> +  image_transport::Publisher debug_image_pub_left_;
Consider concatenating multiple debug images into one for easier debugging.

2017-06-29 00:39 UTC, DSsoto commented on perception/sub8_perception/include/sub8_perception/start_gate.hpp
> +  mil_vision::ImageWithCameraInfo left_most_recent, right_most_recent;
Did you try using ROSCameraStream? it makes a lot of things more convenient, adds buffer functionality. Heres a [simple demo](https://github.com/uf-mil/mil_common/blob/70af0ae7832b2863a4d6c7251fd20599fa6ace84/perception/mil_vision/src/camera_stream_demo.cpp).

2017-06-30 11:01 UTC, RustyBamboo commented
uf_mil/mil_common#74

2017-07-04 03:47 UTC, kev-the-dev requested changes
Good work on the refactoring. Got a few changes. 

Also, this is such a big program for this perception task, it should definitely have at least one full rostest where an image or a bag is played and the 2d segmentation is verified and 3d pose is checked for sanity. This way we can make sure 700 line diffs don't break things. Checkout the [test for path marker](https://github.com/uf-mil/SubjuGator/blob/master/perception/sub8_perception/test/test_path_marker.py) for reference

2017-07-04 03:47 UTC, ironmig commented on command/sub8_missions/missions/start_gate.py
> +FACTOR_DISTANCE_BEFORE = 1.5
Add comments describing what this does, what units it is in

2017-07-04 03:47 UTC, ironmig commented on command/sub8_missions/missions/start_gate.py
> +    yield sub.move.set_position(point_before).zero_roll_and_pitch().go(speed=SPEED)
You should add ```.look_at(position)``` so it faces through the gate during the move

2017-07-04 03:47 UTC, ironmig commented on command/sub8_missions/missions/start_gate.py
> +    point_before = np.array(
Isn't position already a numpy array?

2017-07-04 03:47 UTC, ironmig commented on perception/sub8_perception/src/sub8_perception/start_gate.cpp
> +  dt_ = 1 / 10;
Are you sure this isn't 0 because in integer rounding?

2017-07-04 11:10 UTC, RustyBamboo commented on perception/sub8_perception/src/sub8_perception/start_gate.cpp
> +  dt_ = 1 / 10;
Yup, fixed.

2017-07-04 21:31 UTC, RustyBamboo commented
Added a base class for stereo

2017-07-05 18:45 UTC, kev-the-dev commented on perception/sub8_perception/nodes/torpedo_board.cpp
> +void mil_tools::combinations(uint8_t n, uint8_t k, vector<vector<uint8_t> > &idx_array)
You should remove the function definitions for these two from torpedo board now that they're in mil common.

2017-07-05 18:45 UTC, kev-the-dev commented on perception/sub8_perception/src/sub8_vision_lib/stereo_base.cpp
> +  if (std::count(correspondence_pair_idxs.begin(), correspondence_pair_idxs.end(), -1) != 0)
```correspondence_pair_idxs.size()```?

2017-07-06 16:06 UTC, RustyBamboo commented on perception/sub8_perception/src/sub8_vision_lib/stereo_base.cpp
> +  if (std::count(correspondence_pair_idxs.begin(), correspondence_pair_idxs.end(), -1) != 0)
It's checking if there are any -1 in the vector

2017-07-06 20:28 UTC, kev-the-dev approved these changes

2017-07-06 20:32 UTC, merged