SIM: Add lights, Add tower model, restructure course
uf-mil/SubjuGator pull request #307
Opened 2017-07-18 21:36 UTC by Grymestone

Added lights to fix the lighting issues, added what I think are the last of the models for the competition and ordered the simulator so that it follows the course of the actual competition. Everything should be in there.

2017-07-20 01:28 UTC, RustyBamboo approved these changes
Tubular isn't the most intuitive naming. Maybe something like tower_tubes?

2017-07-21 23:08 UTC, kev-the-dev requested changes
Thanks for the progress. Got a few more things before the course can be used to test chained missions.

Looks like this breaks the teleport option in move_command. Please either hard code in the new numbers or (better) refactor the command so it teleports based on the state of the gazebo model (like fake perception does). If I designed it, I would structure the yaml like this:
```
# For each teleport location
torpedoboard:
    model: squilliamson
    offset: -2.0 0.0 1.0 # Offset from model position to teleport sub to, x y z
...
```

2017-07-21 23:08 UTC, ironmig commented on simulation/sub8_gazebo/launch/duck.launch
> +      -x 3.22 -y 26.58 -z -2 -Z -1.57 -model start_gate"
This new location doesn't give much room to see the gate if the sub starts behind it.

Also, can you move the first path marker to be in front of the start gate and point towards buoys? This is how the course at the transdec will be.

2017-07-21 23:13 UTC, kev-the-dev requested changes

2017-07-21 23:13 UTC, ironmig commented on simulation/sub8_gazebo/launch/duck.launch
> +        -x 38.8 -y 2 -z 0 -Z -1.57 -model octogon"
Also noticed that the beach balls need to be moved too, as they're just floating in no where now

2018-05-31 12:52 UTC, closed without merging

2018-05-31 12:52 UTC, RustyBamboo commented
Branch was updated to different code